library(dplyr)
library(lubridate)
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "household_power_consumption.zip")
unzip("household_power_consumption.zip")
power_consumption<- read.table("household_power_consumption.txt", sep=";", header = TRUE, stringsAsFactors = FALSE)
power_consumption<-subset(power_consumption, Date == "1/2/2007" | Date == "2/2/2007")
na_if(power_consumption, "?")
power_consumption$Global_active_power<- as.numeric(power_consumption$Global_active_power)
png("plot2.png", width= 480, height = 480)
plot(dmy_hms(paste(power_consumption$Date, power_consumption$Time, sep=" ")), power_consumption$Global_active_power, type="n", ylab= "Global Active Power (kilowatts)", xlab= "")
lines(dmy_hms(paste(power_consumption$Date, power_consumption$Time, sep=" ")), power_consumption$Global_active_power)
dev.off()
